### ISSUE TITLE
After install i am getting erro.

### ISSUE THREAD

**Issue by Vinothapplife** [jamzi/instagram-firebase#1]
Thanks for your source and videos. it's very useful for angularfire and ionic2. 

![ionic](https://cloud.githubusercontent.com/assets/8506362/17675599/04cea95e-6348-11e6-8cfc-b2359a72304d.png)

When i run "ionic upload" , i am getting this error. Please advise this

**Comment by jamzi** [comment]
Hi Vinothapplife,

Thank you for your kind words.

These are just some of the Typescript errors probably due to definition files. Can you make it run on your device or is this blocking the deploy?

**Comment by Vinothapplife** [comment]
@jamzi Thanks for your reply. Not blocking the deployment but i am trying to resolve it from our end.
